export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENT = "GET_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const ADD_STUDENT = "ADD_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";

export const GET_ADMINS = "GET_ADMINS";
export const GET_ADMIN = "GET_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const ADD_ADMIN = "ADD_ADMIN";
export const UPDATE_ADMIN = "UPDATE_ADMIN";

export const GET_COURSES = "GET_COURSES";
export const GET_COURSE = "GET_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const ADD_COURSE = "ADD_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";

export const GET_COURSES_BY_STUDENT = "GET_COURSES_BY_STUDENT";
export const GET_STUDENTS_BY_COURSE = "GET_STUDENTS_BY_COURSE";
export const GET_ALL_STUDENT_COURSE = "GET_ALL_STUDENT_COURSE";
export const GET_STUDENT_COURSE = "GET_STUDENT_COURSE";
export const ADD_STUDENT_COURSE = "ADD_STUDENT_COURSE";
export const DELETE_STUDENT_COURSE = "DELETE_STUDENT_COURSE";

export const GET_ERRORS = "GET_ERRORS";
export const DELETE_ERRORS = "DELETE_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_DATA_LOADED = "USER_DATA_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


